version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.23.4
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test ./... -v

  docker-build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
      - checkout
      - run:
          name: Build and Tag Docker Image
          command: docker build -t myapp .
      - run:
          name: List Docker Images
          command: docker images

workflows:
  version: 2
  build-and-docker:
    jobs:
      - build
      - docker-build
